### ISSUE TITLE
Freeze on world gen

### ISSUE THREAD

**Issue by Mr-Syntax** [bl4ckscor3/GetItTogetherDrops#2]
i have no clue why but after adding your mod i had a crash while exploring the overworld

now im not 100% its your mods fault but it seems to have stopped after removing it so im pretty certain

my pack has 300 mods so i know its a pretty big ask but it would be nice if you could make it work with my pack 

https://www.curseforge.com/minecraft/modpacks/chosencraft

**Comment by bl4ckscor3** [comment]
Please post the crash report.

**Comment by bl4ckscor3** [comment]
I've added Get It Together, Drops! to the pack you linked, and i was able to join a world and fly around for some time just fine. This does not look like a problem with GITD.
