### ISSUE TITLE
[1.12] No longer listed in the client

### ISSUE THREAD

**Issue by Sereath** [bl4ckscor3/GetItTogetherDrops#4]
Is it intentional that the mod no longer appears in the mod list? I also noticed that there wasn't a new config file being generated after updating.

1.0

![image](https://user-images.githubusercontent.com/54506307/162643661-58e49620-faae-4f52-adef-a40719a6edc8.png)

1.0.1

![image](https://user-images.githubusercontent.com/54506307/162643663-0227b738-a1a7-46cd-9847-631af6d84fc7.png)

![image](https://user-images.githubusercontent.com/54506307/162643910-46eacfcf-6ffe-4094-9051-a80a8530a468.png)

Modlist dump from TellMe after updating:

https://gist.github.com/Aeron216/09fb230ac4097d5bab1164644c5e0318

**Comment by bl4ckscor3** [comment]
Sorry, I made a mistake when fixing the mod being required on the client when installed on a server (it should only ever need to be installed server side), resulting in it not being loaded on the client at all. That's of course not desirable when wanting to use the mod in singleplayer.
